spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cleanbook
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  datasource:
#    url: jdbc:mysql://localhost:3306/sitedb
#    username: root
#    password: 98limchaemin
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        #          show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  # data.sql 추가
  # 내장형 db
    defer-datasource-initialization: true
  # 그외에서도 동작
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-validity-in-seconds: 10
  refresh-token-validity-in-seconds: 86400
